robotbit.rgb().showColor(neopixel.colors(NeoPixelColors.Red))
basic.pause(1000)
robotbit.rgb().showColor(neopixel.colors(NeoPixelColors.Yellow))
basic.pause(1000)
robotbit.rgb().showColor(neopixel.colors(NeoPixelColors.Green))
basic.pause(1000)
